version: 2

models:
    - name: stg_local_bike__brands
      description: "This model contains information about brands"
      docs:
        show: true
      columns:
          - name: brand_id
            description: "Primary key, unique identifier for each brand"
            tests:
                - unique
                - not_null          

    - name: stg_local_bike__categories
      description: "This model contains information about categories"
      docs:
        show: true
      columns:
          - name: category_id
            description: "Primary key, unique identifier for each category"
            tests:
                - unique
                - not_null

    - name: stg_local_bike__customers
      description: "This model contains information about customers"
      docs:
        show: true
      columns:
          - name: customer_id
            description: "Primary key, unique identifier for each customer"
            tests:
                - unique
                - not_null

    - name: stg_local_bike__orders
      description: "This model contains information about orders"
      docs:
        show: true
      columns:
          - name: order_id
            description: "Primary key, unique identifier for each order"
            tests:
                - unique
                - not_null
          - name: store_id
            description: "Foreign key linking the order to the corresponding store."
            tests:
              - relationships:
                  name: store_id_foreign_key_in_stg_local_bike__stores
                  to: ref('stg_local_bike__stores')
                  field: store_id
          - name: staff_id
            description: "Foreign key linking the order to the corresponding staff."
            tests:
              - relationships:
                  name: staff_id_foreign_key_in_stg_local_bike__staffs
                  to: ref('stg_local_bike__staffs')
                  field: staff_id  

    - name: stg_local_bike__order_items
      description: "This model contains information about each item included in a order"
      docs:
        show: true
      columns:
          - name: order_item_id
            description: "Primary key, unique identifier for each order item"
            tests:
                - unique
                - not_null
          - name: order_id
            description: "Foreign key linking the order item to the corresponding order."
            tests:
              - relationships:
                  name: order_id_foreign_key_in_dans_stg_local_bike__orders
                  to: ref('stg_local_bike__orders')
                  field: order_id

    - name: stg_local_bike__products
      description: "This model contains information about products"
      docs:
        show: true
      columns:
          - name: product_id
            description: "Primary key, unique identifier for each product"
            tests:
                - unique
                - not_null

    - name: stg_local_bike__staffs
      description: "This model contains information about staffs"
      docs:
        show: true
      columns:
          - name: staff_id
            description: "Primary key, unique identifier for each staff"
            tests:
                - unique
                - not_null

    - name: stg_local_bike__stocks
      description: "This model contains information about stocks of product"
      docs:
        show: true
      columns:
          - name: stock_id
            description: "Primary key, unique identifier for each stock of product"
            tests:
                - unique
                - not_null
          - name: product_id
            description: "Foreign key linking the stock to the corresponding product."
            tests:
              - relationships:
                  name: product_id_foreign_key_in_stg_local_bike__products
                  to: ref('stg_local_bike__products')
                  field: product_id

    - name: stg_local_bike__stores
      description: "This model contains information about stores"
      docs:
        show: true
      columns:
          - name: store_id
            description: "Primary key, unique identifier for each store"
            tests:
                - unique
                - not_null